name: Badges
version: '1.0-SNAPSHOT'
main: com.batoni.badges.Badges
api-version: '1.21'
commands:
  badge:

permissions:
  badges.list:
    default: true
  badges.grant:
    default: true
  badges.take:
    default: true
  badges.wear:
    default: true
  badges.remove:
    default: true